###
POST {{proto}}{{host}}:{{port}}/404
X-Mm-Auth-Token: ABC
###
POST {{proto}}{{host}}:{{port}}/ok
X-Mm-Auth-Token: QWE
###
POST {{proto}}{{host}}:{{port}}/fail
X-Mm-Auth-Token: ABC
###
POST {{proto}}{{host}}:{{port}}/section/file
X-Mm-Auth-Token: ABC
###
POST {{proto}}{{host}}:{{port}}/section
X-Mm-Auth-Token: ABC
###
POST {{proto}}{{host}}:{{port}}/section/
X-Mm-Auth-Token: ABC
###
GET {{proto}}{{host}}:{{port}}/ok?one=1&two=2
X-Mm-Auth-Token: ABC
###
GET {{proto}}{{host}}:{{port}}/ok/one/1/two/2
X-Mm-Auth-Token: ABC
###
GET {{proto}}{{host}}:{{port}}/file
X-Mm-Auth-Token: ABC
###
GET {{proto}}{{host}}:{{port}}/delay
X-Mm-Auth-Token: ABC
###
